# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

name: Integration test
description: Run the integration tests against a single version of k8s and Vault
inputs:
  k8s-version:
    description: 'Kubernetes version to use for the kind cluster'
    required: true
  vault-version:
    description: 'Vault version to use for the tests'
    required: true
  artifact-name:
    description: 'Name of the tarball artifact to download'
    default: vault-csi-provider-image
  tarball-file:
    description: 'Name of the tarball file in the artifact to load'
    required: true
  image-type:
    description: 'Type of the image to load (e.g. "alpine" or "ubi")'
    default: alpine
  vault-license:
    description: 'Vault license to use for enterprise tests'
    required: true
  kind-cluster-name:
    description: 'Name of the kind cluster to create and test against'
    default: 'kind'
  extra-vault-values:
    description: 'Extra Helm values to pass to the Vault Helm installation'
    default: ''
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm install -g bats@${{ env.BATS_VERSION }}
      shell: bash
    - run: bats -v
      shell: bash

    - name: Create Kind Cluster
      uses: helm/kind-action@a1b0e391336a6ee6713a0583f8c6240d70863de3 # v1.12.0
      with:
        cluster_name: ${{ inputs.kind-cluster-name }}
        config: test/bats/configs/kind/config.yaml
        node_image: kindest/node:v${{ inputs.k8s-version }}
        version: ${{ env.KIND_VERSION }}

    - name: Create kind export log root
      id: create_kind_export_log_root
      shell: bash
      run: |
        vault_flavor=ent
        log_artifact_name="kind-${{ inputs.kind-cluster-name }}-$(git rev-parse --short ${{ github.sha }})-${{ inputs.k8s-version }}-${{ inputs.vault-version }}-${vault_flavor}-${{ inputs.image-type }}-helm-logs"
        log_root="/tmp/${log_artifact_name}"
        mkdir -p "${log_root}"
        echo "log_root=${log_root}" >> $GITHUB_OUTPUT
        echo "log_artifact_name=${log_artifact_name}" >> $GITHUB_OUTPUT

    - uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
      with:
        name: ${{ inputs.artifact-name }}

    - name: Load vault-csi-provider dev image
      shell: bash
      run: docker image load --input ${{ inputs.tarball-file }}

    - name: bats tests
      shell: bash
      env:
        VAULT_LICENSE: ${{ inputs.vault-license }}
      run: make e2e-teardown e2e-setup e2e-test DISPLAY_SETUP_TEARDOWN_LOGS=true VAULT_VERSION="${{ inputs.vault-version }}" EXTRA_VAULT_VALUES="${{ inputs.extra-vault-values }}"

    - name: export kind cluster logs
      if: always()
      shell: bash
      run: |
        kind export logs --name ${{ inputs.kind-cluster-name }} ${{ steps.create_kind_export_log_root.outputs.log_root }}

    - name: Store kind cluster logs
      if: success()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ${{ steps.create_kind_export_log_root.outputs.log_artifact_name }}
        path: ${{ steps.create_kind_export_log_root.outputs.log_root }}

    - name: Store kind cluster logs failure
      if: failure()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: ${{ steps.create_kind_export_log_root.outputs.log_artifact_name }}-failed
        path: ${{ steps.create_kind_export_log_root.outputs.log_root }}
