# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Integration test
description: Run the integration tests against a single version of k8s and Vault
inputs:
  k8s-version:
    description: 'Kubernetes version to use for the kind cluster'
    required: true
  vault-version:
    description: 'Vault version to use for the tests'
    required: true
  tarball-file:
    description: 'Name of the tarball file artifact to download'
    required: true
  vault-license:
    description: 'Vault license to use for enterprise tests'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
    - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm install -g bats@${{ env.BATS_VERSION }}
      shell: bash
    - run: bats -v
      shell: bash

    - name: Create Kind Cluster
      uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140 # v1.8.0
      with:
        cluster_name: kind
        config: test/bats/configs/kind/config.yaml
        node_image: kindest/node:v${{ inputs.k8s-version }}
        version: ${{ env.KIND_VERSION }}

    - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      with:
        name: vault-csi-provider-image

    - name: Load vault-csi-provider dev image
      shell: bash
      run: docker image load --input ${{ inputs.tarball-file }}

    - name: bats tests
      shell: bash
      env:
        VAULT_LICENSE: ${{ inputs.vault-license }}
      run: make e2e-teardown e2e-setup e2e-test DISPLAY_SETUP_TEARDOWN_LOGS=true VAULT_VERSION="${{ inputs.vault-version }}"
