# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Integration test
description: Run the integration tests against a single version of k8s and Vault
inputs:
  k8s-version:
    description: 'Kubernetes version to use for the kind cluster'
    required: true
  vault-version:
    description: 'Vault version to use for the tests'
    required: true
  tarball-file:
    description: 'Name of the tarball file artifact to download'
    required: true
  vault-license:
    description: 'Vault license to use for enterprise tests'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm install -g bats@${{ env.BATS_VERSION }}
      shell: bash
    - run: bats -v
      shell: bash

    - name: Create Kind Cluster
      uses: helm/kind-action@0025e74a8c7512023d06dc019c617aa3cf561fde # v1.10.0
      with:
        cluster_name: kind
        config: test/bats/configs/kind/config.yaml
        node_image: kindest/node:v${{ inputs.k8s-version }}
        version: ${{ env.KIND_VERSION }}

    - uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
      with:
        name: vault-csi-provider-image

    - name: Load vault-csi-provider dev image
      shell: bash
      run: docker image load --input ${{ inputs.tarball-file }}

    - name: bats tests
      shell: bash
      env:
        VAULT_LICENSE: ${{ inputs.vault-license }}
      run: make e2e-teardown e2e-setup e2e-test DISPLAY_SETUP_TEARDOWN_LOGS=true VAULT_VERSION="${{ inputs.vault-version }}"
